on: 
  workflow_dispatch:
    inputs:
     region:
        type: choice
        description: select region
        required: true
        options:
        - foo
        - bar
        - baz
     country:
        type: choice
        description: select environment
        required: true
        options:
        - foo
        - bar
        - baz
        
        
        

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "${{ github.event.inputs.region }}_${{ github.event.inputs.country }}"
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
